# Tensores

Aqui vimos los tensores, que basicamente son estructuras de datos como las tablas, pero
que pueden llegar a varias dimensiones.

- Se implementan con numpy
- Tienen operaciones elemento a elemento, o a nivel de matriz

In [1]:
import numpy as np


In [2]:
np.array([0])

# Este es un tensor de dimension 0


array([0])

In [4]:
np.array([1, 2, 3])

# Este es un tensor de dimension 1


array([1, 2, 3])

In [8]:
np.array([[1, 2, 3], [1, 2, 3]])

# Este es un tensor de dimension 2

array([[1, 2, 3],
       [1, 2, 3]])

In [12]:
tres = np.array([[[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]]])

print(tres)
print(tres.shape)


# Este es un tensor de dimension 3. (Es como una matriz de forma 2, 3, pero con 2 hojas!)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
(2, 2, 3)


# Implementacion

Ocupa TensorFlow (para ocupar tensores) y Keras (Permite ocupar tensorflow de forma mas facil)

# Terminos de redes Neuronales

## Perceptron

Fue la primera neurona que se utilizo! Hace mushosanios

## Anatomia de un Perceptron

Tiene neuronas. Las neuronas reciben un input, y dan un output. 

1. Como input reciben una serie de atributos (por ej: estatura, calorias comidas, alimentos comidos, etc), multiplicados por pesos aleatorios.

2. Luego, la neurona recibe todo esos inputs, y luego los pasa por una funcion de activacion
(es arbitraria, puede tomar los datos y sumarlos, multiplicarlos, etc)

3. Finalmente, la neurona da el output, basado en el paso de los atributos (multiplicados por 
los pesos ALEATORIOS) por la funcion de activacion!

4. Por ultimo, se calcula la funcion de perdida y se mide el desempeno del modelo (por ejemplo:
se calcula el MAE)

5. Basado en la funcion de perdida, y utilizando gradiente descendiente, se actualizan los pesos
de cada atributo y se optimiza el modelo!

# Funciones de activacion

Hay varias, salen en Wkipedia

In [13]:
import tensorflow as tf
import keras

from keras.models import Sequential
from keras.layers import Dense

print(keras.backend.backend())

tensorflow


In [16]:
model = Sequential()  # Esto es para general un modelo secuencial (neurona luego de neurona!)

# La primera neurona del modelo!

model.add(
    Dense(
        1,
        activation="linear", # Funcion de activacion de la neruona, en este caso lineal
        use_bias=False, # Ignora el sesgo
        kernel_initializer="uniform", 
        input_shape=[1], # Forma en que vienen los datos
        name="entrada",
    )
)

# Esta es la ultima nuerona del modelo!

model.add(
    Dense(
        activation="linear",
        input_dim=1,
        use_bias=False,
        name='salida',
        units=1
    )
)