# Tensores

Aqui vimos los tensores, que basicamente son estructuras de datos como las tablas, pero
que pueden llegar a varias dimensiones.

- Se implementan con numpy
- Tienen operaciones elemento a elemento, o a nivel de matriz

In [1]:
import numpy as np


In [2]:
np.array([0])

# Este es un tensor de dimension 0


array([0])

In [4]:
np.array([1, 2, 3])

# Este es un tensor de dimension 1


array([1, 2, 3])

In [8]:
np.array([[1, 2, 3], [1, 2, 3]])

# Este es un tensor de dimension 2

array([[1, 2, 3],
       [1, 2, 3]])

In [12]:
tres = np.array([[[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]]])

print(tres)
print(tres.shape)


# Este es un tensor de dimension 3. (Es como una matriz de forma 2, 3, pero con 2 hojas!)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
(2, 2, 3)


# Implementacion

Ocupa TensorFlow (para ocupar tensores) y Keras (Permite ocupar tensorflow de forma mas facil)

# Terminos de redes Neuronales

## Perceptron

Fue la primera neurona que se utilizo! Hace mushosanios

## Anatomia de un Perceptron

Tiene neuronas. Las neuronas reciben un input, y dan un output. 

1. Como input reciben una serie de atributos (por ej: estatura, calorias comidas, alimentos comidos, etc), multiplicados por pesos aleatorios.

2. Luego, la neurona recibe todo esos inputs, y luego los pasa por una funcion de activacion
(es arbitraria, puede tomar los datos y sumarlos, multiplicarlos, etc)

3. Finalmente, la neurona da el output, basado en el paso de los atributos (multiplicados por 
los pesos ALEATORIOS) por la funcion de activacion!. Luego, se llega al final de la red y se obtiene
un output.

4. Al output de toda la red se le puede calcular la funcion de perdida (MAE por ej).

5. Basado en la funcion de perdida, y utilizando gradiente descendiente, se actualizan los pesos
de cada atributo y se optimiza el modelo!

## Diferencia con Boosting

- En Boosting se conservan todo el camino de arboles generados hasta llegar al arbol mas optimo. Luego,
se predice tomando en cuenta todos los arboles en el camino!

- En las redes neuronales optimizamos los parametros a lo largo de muchas corrida. Sin embargo,
cuando ya llegamos a un modelo optimo, solamente nos quedamos con ese modelo y solamente ese predice!

# Funciones de activacion

Hay varias, salen en Wkipedia. Pero son las funciones que tienen cada neurona, y que procesan
los datos de input. Estas funciones generan un output, y este es el output de la neurona.

In [13]:
import tensorflow as tf
import keras

from keras.models import Sequential
from keras.layers import Dense

print(keras.backend.backend())

tensorflow


# Inicializacion de los modelos

In [17]:
model = Sequential()  # Esto es para general un modelo secuencial (neurona luego de neurona!)

# La primera neurona del modelo!

model.add(
    Dense(
        1,
        activation="linear", # Funcion de activacion de la neruona, en este caso lineal
        use_bias=False, # Ignora el sesgo
        kernel_initializer="uniform", 
        input_shape=[1], # Forma en que vienen los datos
        name="entrada",
    )
)

# Esta es la ultima nuerona del modelo!

model.add(
    Dense(
        activation="linear",
        input_dim=1,
        use_bias=False,
        name='salida',
        units=1
    )
)

In [18]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 entrada (Dense)             (None, 1)                 1         
                                                                 
 salida (Dense)              (None, 1)                 1         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [21]:
from keras.optimizers import SGD

model.compile(optimizer=SGD(learning_rate=0.1), loss='mse')

In [22]:
m = 30
intercept_true = 0.5
slope_true = 1.5
x = slope_true + np.random.rand(m, 1)
y = intercept_true + (slope_true * x)

In [25]:
model.fit(x, y, epochs=1000, verbose=0)

# con los epochs se le dice al modelo que haga 1000 iteraciones para optimizar los parametros
# del modelo.

# Aqui solamente se optimiza un peso (solamente el de la entrada, ya que la de salida
# carece de pesos (pasa en "banda" el resultado)

In [24]:
model.get_weights()

[array([[-1.4313426]], dtype=float32), array([[-1.4313426]], dtype=float32)]

In [29]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y, model.predict(x))

1/1 [==============================] - 0s 11ms/step


1.6463939728335388